name: nutrigram 

on:  

  push: 

    branches: 

      - main #here we choose to deploy only when a push is detected on the main branch. 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    env: 

      AWS_S3_BUCKET: nutrigram.fit 

      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}} 

      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}} 

      aws-region: us-east-1 # Use your bucket region here 

    strategy: 

      matrix: 

        node-version: [16.15.x] 

    steps: 

      - uses: actions/checkout@master 

      - name: Use Node.js ${{ matrix.node-version }} 

        uses: actions/setup-node@v1 

        with: 

          node-version: ${{ matrix.node-version }} 
     # - name: changing directory 

       # run: cd web 
        
      - name: Install Dependencies 

        run: npm install
        
      

# Deploy to S3 

# This is a third party action used to sync our production build app with the AWS S3 bucket 

# For security purpose I am using secrets configured in project repo setting. 

      - name: Deploy to S3 

        uses: jakejarvis/s3-sync-action@v0.5.1 

        with: 

          # --acl public read => makes files publicly readable(i.e. makes sure that your bucket settings are also set to public) 

          # --delete => permanently deletes files in S3 bucket that are not present in latest build 

          args: --acl public-read --delete 

        env: 

          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }} # S3 bucket name 

          # note: use IAM role with limited role for below access-key-id and secret-access-key 

          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Access Key ID 

          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Access Secret Key 

          SOURCE_DIR: "build/emission-portal/" # build folder
